### PR TITLE
feat(equipment): Add equipment to entity snapshots

### PR DESCRIPTION
**Pull request by LarsKoelpin**
Hi,
as stated in #38 I'd like to have the equipment in he snapshots.

The implementation seems to work, but the test is failing and I'm not really sure how to exactly fix them.
(something with default value comparison)

### CODE REVIEW

**Comment by markus-wa** [comment]
Ahh yes, classic 😄

Check out this one 🙂 https://github.com/markus-wa/cs-demo-minifier/blob/master/replay/nondefault/nondefault_replay.go

You'll need to add the new data in the `init()` func. The package doc there also explains what it is.

**Comment by LarsKoelpin** [comment]
If I understood correctly, I just have to add ?
```golang		
Equipment:     make([]rep.EntityEquipment, 0),
```
Unfortunately, this results in the same test failure :(

**Comment by markus-wa** [comment]
You will need at least one `EntityEquipment` entry, not an empty slice. (this is due to `omitempty`)

**Comment by LarsKoelpin** [comment]
If you have  some spare time, would you have a look on the failing snapshots tests related to the protobuf files, as I never have worked with protobuf.

I guess somehow the build get stuck?!

**Comment by markus-wa** [comment]
this should do it: 066b9e08c067e2c6a09e11259141db8058ebd8c9 :slightly_smiling_face: 

protobuf mappings for new fields need to be added manually (while events are just generic key/value pairs, so new  ones are automatically mapped)

**Comment by markus-wa** [comment]
merged and released: https://github.com/markus-wa/cs-demo-minifier/releases/tag/v0.4.2

**Comment by LarsKoelpin** [comment]
nice! ty

**Comment by markus-wa** [comment]
Thank YOU! @LarsKoelpin  😄😄

**Pull request merged**
